// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hotel_be.ModelFromDB;

#nullable disable

namespace hotel_be.Migrations
{
    [DbContext(typeof(DBCnhom4))]
    [Migration("20250311083611_UpdateBookingSchema")]
    partial class UpdateBookingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hotel_be.ModelFromDB.TblBooking", b =>
                {
                    b.Property<Guid>("BBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("b_BookingID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BBookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("b_BookingStatus");

                    b.Property<DateTime?>("BCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("b_CreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("BDeposit")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("b_Deposit");

                    b.Property<Guid>("BGuestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("b_GuestID");

                    b.Property<decimal?>("BTotalMoney")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("b_TotalMoney");

                    b.HasKey("BBookingId")
                        .HasName("PK__tbl_Book__63A328519228D519");

                    b.HasIndex("BGuestId");

                    b.ToTable("tbl_Bookings");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblBookingRoom", b =>
                {
                    b.Property<Guid>("BrBookingRoomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("br_BookingRoomsID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BrBookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("br_BookingID");

                    b.Property<DateTime>("BrCheckInDate")
                        .HasColumnType("datetime")
                        .HasColumnName("br_CheckInDate");

                    b.Property<DateTime>("BrCheckOutDate")
                        .HasColumnType("datetime")
                        .HasColumnName("br_CheckOutDate");

                    b.Property<Guid>("BrRoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("br_RoomID");

                    b.HasKey("BrBookingRoomsId")
                        .HasName("PK__tbl_Book__0D1D3016859B4CCE");

                    b.HasIndex("BrBookingId");

                    b.HasIndex("BrRoomId");

                    b.ToTable("tbl_BookingRooms");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblBookingService", b =>
                {
                    b.Property<Guid>("BsBookingServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bs_BookingServicesID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BsBookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bs_BookingID");

                    b.Property<DateTime?>("BsCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("bs_CreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("BsQuantity")
                        .HasColumnType("int")
                        .HasColumnName("bs_Quantity");

                    b.Property<Guid>("BsServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bs_ServiceID");

                    b.HasKey("BsBookingServicesId")
                        .HasName("PK__tbl_Book__596EDF990FEA40A2");

                    b.HasIndex("BsBookingId");

                    b.HasIndex("BsServiceId");

                    b.ToTable("tbl_BookingServices");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblEmployee", b =>
                {
                    b.Property<Guid>("EEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("e_EmployeeID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("EEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("e_Email");

                    b.Property<string>("EFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("e_FirstName");

                    b.Property<string>("ELastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("e_LastName");

                    b.Property<string>("EPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("e_PhoneNumber");

                    b.Property<string>("EPosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("e_Position");

                    b.Property<decimal>("ESalary")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("e_Salary");

                    b.HasKey("EEmployeeId")
                        .HasName("PK__tbl_Empl__C8C1ED27F2E0DF2F");

                    b.HasIndex(new[] { "EEmail" }, "UQ__tbl_Empl__3908DC82E918A11D")
                        .IsUnique();

                    b.ToTable("tbl_Employees");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblFloor", b =>
                {
                    b.Property<Guid>("FFloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("f_FloorID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("FFloor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("f_Floor");

                    b.HasKey("FFloorId")
                        .HasName("PK__tbl_Floo__051B7217F729A4C1");

                    b.ToTable("tbl_Floors");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblGood", b =>
                {
                    b.Property<Guid>("GGoodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("g_GoodsID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("g_Category");

                    b.Property<decimal>("GCostPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("g_CostPrice");

                    b.Property<string>("GCurrency")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("g_Currency");

                    b.Property<string>("GGoodsName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("g_GoodsName");

                    b.Property<int?>("GQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("g_Quantity");

                    b.Property<decimal>("GSellingPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("g_SellingPrice");

                    b.Property<string>("GUnit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("g_Unit");

                    b.HasKey("GGoodsId")
                        .HasName("PK__tbl_Good__F3C565BF23D59FE8");

                    b.ToTable("tbl_Goods");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblGuest", b =>
                {
                    b.Property<Guid>("GGuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("g_GuestID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("g_Email");

                    b.Property<string>("GFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("g_FirstName");

                    b.Property<string>("GLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("g_LastName");

                    b.Property<string>("GPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("g_PhoneNumber");

                    b.HasKey("GGuestId")
                        .HasName("PK__tbl_Gues__246FE39FA3C461FC");

                    b.HasIndex(new[] { "GEmail" }, "UQ__tbl_Gues__317ADEF737721475")
                        .IsUnique()
                        .HasFilter("[g_Email] IS NOT NULL");

                    b.ToTable("tbl_Guests");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblImportGood", b =>
                {
                    b.Property<Guid>("IgImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ig_ImportID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("IgCurrency")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ig_Currency");

                    b.Property<DateTime?>("IgImportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ig_ImportDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("IgSumPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("ig_SumPrice");

                    b.Property<string>("IgSupplier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ig_Supplier");

                    b.HasKey("IgImportId")
                        .HasName("PK__tbl_Impo__80DAB00143D209F2");

                    b.ToTable("tbl_ImportGoods");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblImportGoodsDetail", b =>
                {
                    b.Property<Guid>("IgdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("igd_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("IgdCostPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("igd_CostPrice");

                    b.Property<Guid>("IgdGoodsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("igd_GoodsID");

                    b.Property<Guid>("IgdImportId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("igd_ImportID");

                    b.Property<int>("IgdQuantity")
                        .HasColumnType("int")
                        .HasColumnName("igd_Quantity");

                    b.HasKey("IgdId")
                        .HasName("PK__tbl_Impo__43F44C2769D6E00D");

                    b.HasIndex("IgdGoodsId");

                    b.HasIndex("IgdImportId");

                    b.ToTable("tbl_ImportGoodsDetails");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblPartner", b =>
                {
                    b.Property<Guid>("PPartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("p_PartnerID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("PAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("p_Address");

                    b.Property<string>("PEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("p_Email");

                    b.Property<string>("PPartnerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("p_PartnerName");

                    b.Property<string>("PPartnerType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("p_PartnerType");

                    b.Property<string>("PPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("p_PhoneNumber");

                    b.HasKey("PPartnerId")
                        .HasName("PK__tbl_Part__AE7A57A2AFFBA644");

                    b.HasIndex(new[] { "PEmail" }, "UQ__tbl_Part__1DFC0D6D78CD48CF")
                        .IsUnique()
                        .HasFilter("[p_Email] IS NOT NULL");

                    b.ToTable("tbl_Partner");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblPayment", b =>
                {
                    b.Property<Guid>("PPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("p_PaymentID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("PAmountPaid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("p_AmountPaid");

                    b.Property<Guid>("PBookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("p_BookingID");

                    b.Property<DateTime?>("PPaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("p_PaymentDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PPaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("p_PaymentMethod");

                    b.HasKey("PPaymentId")
                        .HasName("PK__tbl_Paym__8C19796638122A06");

                    b.HasIndex("PBookingId");

                    b.ToTable("tbl_Payments");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblRoom", b =>
                {
                    b.Property<Guid>("RRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("r_RoomID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("RFloorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("r_FloorID");

                    b.Property<decimal>("RPricePerHour")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("r_PricePerHour");

                    b.Property<string>("RRoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("r_RoomNumber");

                    b.Property<string>("RRoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("r_RoomType");

                    b.Property<string>("RStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("r_Status");

                    b.HasKey("RRoomId")
                        .HasName("PK__tbl_Room__7CCD5DBBE6937381");

                    b.HasIndex("RFloorId");

                    b.HasIndex(new[] { "RRoomNumber" }, "UQ__tbl_Room__64AD69DE794F86F1")
                        .IsUnique();

                    b.ToTable("tbl_Rooms");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblService", b =>
                {
                    b.Property<Guid>("SServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("s_ServiceID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("SServiceCostPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("s_ServiceCostPrice");

                    b.Property<string>("SServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("s_ServiceName");

                    b.Property<decimal>("SServiceSellPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("s_ServiceSellPrice");

                    b.HasKey("SServiceId")
                        .HasName("PK__tbl_Serv__982F5085957AF391");

                    b.ToTable("tbl_Services");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblServiceGood", b =>
                {
                    b.Property<Guid>("SgServiceGoodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sg_ServiceGoodsID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("SgGoodsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sg_GoodsID");

                    b.Property<int>("SgQuantity")
                        .HasColumnType("int")
                        .HasColumnName("sg_Quantity");

                    b.Property<Guid>("SgServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sg_ServiceID");

                    b.HasKey("SgServiceGoodsId")
                        .HasName("PK__tbl_Serv__1D5E6B96871F74F4");

                    b.HasIndex("SgGoodsId");

                    b.HasIndex("SgServiceId");

                    b.ToTable("tbl_ServiceGoods");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblBooking", b =>
                {
                    b.HasOne("hotel_be.ModelFromDB.TblGuest", "BGuest")
                        .WithMany("TblBookings")
                        .HasForeignKey("BGuestId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Booki__b_Gue__7BB05806");

                    b.Navigation("BGuest");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblBookingRoom", b =>
                {
                    b.HasOne("hotel_be.ModelFromDB.TblBooking", "BrBooking")
                        .WithMany("TblBookingRooms")
                        .HasForeignKey("BrBookingId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Booki__br_Bo__04459E07");

                    b.HasOne("hotel_be.ModelFromDB.TblRoom", "BrRoom")
                        .WithMany("TblBookingRooms")
                        .HasForeignKey("BrRoomId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Booki__br_Ro__0539C240");

                    b.Navigation("BrBooking");

                    b.Navigation("BrRoom");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblBookingService", b =>
                {
                    b.HasOne("hotel_be.ModelFromDB.TblBooking", "BsBooking")
                        .WithMany("TblBookingServices")
                        .HasForeignKey("BsBookingId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Booki__bs_Bo__0AF29B96");

                    b.HasOne("hotel_be.ModelFromDB.TblService", "BsService")
                        .WithMany("TblBookingServices")
                        .HasForeignKey("BsServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Booki__bs_Se__0BE6BFCF");

                    b.Navigation("BsBooking");

                    b.Navigation("BsService");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblImportGoodsDetail", b =>
                {
                    b.HasOne("hotel_be.ModelFromDB.TblGood", "IgdGoods")
                        .WithMany("TblImportGoodsDetails")
                        .HasForeignKey("IgdGoodsId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Impor__igd_G__7132C993");

                    b.HasOne("hotel_be.ModelFromDB.TblImportGood", "IgdImport")
                        .WithMany("TblImportGoodsDetails")
                        .HasForeignKey("IgdImportId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Impor__igd_I__703EA55A");

                    b.Navigation("IgdGoods");

                    b.Navigation("IgdImport");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblPayment", b =>
                {
                    b.HasOne("hotel_be.ModelFromDB.TblBooking", "PBooking")
                        .WithMany("TblPayments")
                        .HasForeignKey("PBookingId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Payme__p_Boo__00750D23");

                    b.Navigation("PBooking");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblRoom", b =>
                {
                    b.HasOne("hotel_be.ModelFromDB.TblFloor", "RFloor")
                        .WithMany("TblRooms")
                        .HasForeignKey("RFloorId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Rooms__r_Flo__3CBF0154");

                    b.Navigation("RFloor");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblServiceGood", b =>
                {
                    b.HasOne("hotel_be.ModelFromDB.TblGood", "SgGoods")
                        .WithMany("TblServiceGoods")
                        .HasForeignKey("SgGoodsId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Servi__sg_Go__689D8392");

                    b.HasOne("hotel_be.ModelFromDB.TblService", "SgService")
                        .WithMany("TblServiceGoods")
                        .HasForeignKey("SgServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Servi__sg_Se__67A95F59");

                    b.Navigation("SgGoods");

                    b.Navigation("SgService");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblBooking", b =>
                {
                    b.Navigation("TblBookingRooms");

                    b.Navigation("TblBookingServices");

                    b.Navigation("TblPayments");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblFloor", b =>
                {
                    b.Navigation("TblRooms");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblGood", b =>
                {
                    b.Navigation("TblImportGoodsDetails");

                    b.Navigation("TblServiceGoods");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblGuest", b =>
                {
                    b.Navigation("TblBookings");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblImportGood", b =>
                {
                    b.Navigation("TblImportGoodsDetails");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblRoom", b =>
                {
                    b.Navigation("TblBookingRooms");
                });

            modelBuilder.Entity("hotel_be.ModelFromDB.TblService", b =>
                {
                    b.Navigation("TblBookingServices");

                    b.Navigation("TblServiceGoods");
                });
#pragma warning restore 612, 618
        }
    }
}
